language: ruby
branches:
  only: master
script: "./_scripts/deploy.sh"
env:
  global:
    secure: "p0Ix2bjpYJnLGmEUW7mZATiWxTAwp9h1XOl3ZXP0KzrQkrRHuHSJhhtvXcIFRAMAf/wsn/NeIcJbZzPWvgvP3fFD6i8qSQqnp8FmjyZEsOAKCGB+RFQn+t0D5D0ws3fKnah9vsrDYkupz7wI/J+3vX7G2ZMd78MZuubbcxE4szM="
    secure: "mia5KjYq+65kz5hlXazoZ2/ZWt9XPJo/m/6Ej07rV96H8hIS7xrjDvzavBlcJ7cacxDQMJDnvCINAl2OPf0QGvs/ANamou43dAEE77TKOdIWYPBaQtIrzsxg8PFt+J9XBYf23Z3d/Q3+lIRO8ze8mzSoSNc/1susVizzmUlHhG8="
cache: bundler