name: Hugo Tunius - Blog
markdown: kramdown
pygments: true
#encoding: UTF-16
timezone: Europe/Stockholm
exclude: ['config', 'Capfile', 'Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib', 'config']
relative_permalinks: false