name: Hugo Tunius - Blog
markdown: kramdown
highligther: pygments
#encoding: UTF-16
timezone: Europe/Stockholm
exclude: ['config', 'Capfile', 'Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib', 'config', 'vendor']
relative_permalinks: false