name: Hugo Tunius - Blog
markdown: kramdown
highligther: pygments
#encoding: UTF-16
timezone: Europe/Stockholm
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile']
relative_permalinks: false
url: hugotunius.se
author: Hugo Tunius
copyright: Hugo Tunius