name: Hugo Tunius - Blog
markdown: kramdown
highligther: pygments
#encoding: UTF-16
timezone: Europe/Stockholm
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
url: hugotunius.se
author: Hugo Tunius
copyright: Hugo Tunius
gems:
    - jekyll-redirect-from
    - jekyll-feed
sass:
  style: compressed
